// Product data to be inserted via bulk upload
export const bulkProductData = [
  {
    product_code: "H001",
    product_name: "Selfie Stick",
    category: "Kids Special",
    user_for: "Kids" as const,
    mrp: 600,
    discount: 90,
    final_rate: 60,
    stock: 10000,
    description: "Kids Special",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H002",
    product_name: "Photo Flash",
    category: "Kids Special",
    user_for: "Kids" as const,
    mrp: 720,
    discount: 90,
    final_rate: 72,
    stock: 10000,
    description: "Kids Special",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H003",
    product_name: "Amazing Pencil 3 In 1",
    category: "Kids Special",
    user_for: "Kids" as const,
    mrp: 950,
    discount: 90,
    final_rate: 95,
    stock: 10000,
    description: "Kids Special",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H004",
    product_name: "Top Gun 2 pcs",
    category: "Kids Special",
    user_for: "Kids" as const,
    mrp: 1980,
    discount: 90,
    final_rate: 198,
    stock: 10000,
    description: "Kids Special",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H005",
    product_name: "Sharp Shooter Full Crackling Multicolour",
    category: "Kids Special",
    user_for: "Kids" as const,
    mrp: 2390,
    discount: 90,
    final_rate: 239,
    stock: 10000,
    description: "Kids Special",
    content: "Gun 1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H006",
    product_name: "Money Bank",
    category: "Kids Special Blast With Currency",
    user_for: "Kids" as const,
    mrp: 240,
    discount: 90,
    final_rate: 24,
    stock: 10000,
    description: "Kids Special Blast With Currency",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H007",
    product_name: "Magic Money Crorepathi (2 In 1)",
    category: "Kids Special Blast With Currency",
    user_for: "Kids" as const,
    mrp: 3240,
    discount: 90,
    final_rate: 324,
    stock: 10000,
    description: "Kids Special Blast With Currency",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H008",
    product_name: "12 cm Electric Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 350,
    discount: 90,
    final_rate: 35,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H009",
    product_name: "12 cm Color Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 360,
    discount: 90,
    final_rate: 36,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H010",
    product_name: "12 cm Green Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 370,
    discount: 90,
    final_rate: 37,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H011",
    product_name: "12 cm Red Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 380,
    discount: 90,
    final_rate: 38,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H012",
    product_name: "15 cm Electric Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 540,
    discount: 90,
    final_rate: 54,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H013",
    product_name: "30 cm Electric Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 540,
    discount: 90,
    final_rate: 54,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H014",
    product_name: "15 cm Color Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 550,
    discount: 90,
    final_rate: 55,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  {
    product_code: "H015",
    product_name: "30 cm Color Sparklers",
    category: "Sparklers",
    user_for: "Kids" as const,
    mrp: 550,
    discount: 90,
    final_rate: 55,
    stock: 10000,
    description: "Sparklers",
    content: "1Box",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  },
  // Sample of additional products - you can add the full list of H016-H190 here
  {
    product_code: "H051",
    product_name: "Jeyaguru's 3 1/2' (8.89cm) Sky Dancers",
    category: "3 1/2' (8.89 cm) Sky Dancers",
    user_for: "Adult" as const,
    mrp: 3120,
    discount: 90,
    final_rate: 312,
    stock: 10000,
    description: "3 1/2' (8.89 cm) Sky Dancers",
    content: "1Pcs",
    status: "active" as const,
    featured: false,
    rating: 0,
    reviews_count: 0,
    image_url: "",
    video_url: ""
  }
];