// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnviashpkfkfbhyoogiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRudmlhc2hwa2ZrZmJoeW9vZ2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDQyMzcsImV4cCI6MjA3MjMyMDIzN30.5BDtu2N_DTX3OaPda2kf5Ub89ZcjUsbhCAFi4kifDyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});